/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallRouteImport } from './routes/call'
import { Route as CompassRouteImport } from './routes/compass'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibrarySlugRouteImport } from './routes/library/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassRoute = CompassRouteImport.update({
  id: '/compass',
  path: '/compass',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/compass': typeof CompassRoute
  '/deals': typeof DealsRoute
  '/discovery': typeof DiscoveryRoute
  '/outputs': typeof OutputsRoute
  '/playbook': typeof PlaybookRoute
  '/risk': typeof RiskRoute
  '/routing': typeof RoutingRoute
  '/settings': typeof SettingsRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/compass': typeof CompassRoute
  '/deals': typeof DealsRoute
  '/discovery': typeof DiscoveryRoute
  '/outputs': typeof OutputsRoute
  '/playbook': typeof PlaybookRoute
  '/risk': typeof RiskRoute
  '/routing': typeof RoutingRoute
  '/settings': typeof SettingsRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/compass': typeof CompassRoute
  '/deals': typeof DealsRoute
  '/discovery': typeof DiscoveryRoute
  '/outputs': typeof OutputsRoute
  '/playbook': typeof PlaybookRoute
  '/risk': typeof RiskRoute
  '/routing': typeof RoutingRoute
  '/settings': typeof SettingsRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/compass'
    | '/deals'
    | '/discovery'
    | '/outputs'
    | '/playbook'
    | '/risk'
    | '/routing'
    | '/settings'
    | '/library/$slug'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/compass'
    | '/deals'
    | '/discovery'
    | '/outputs'
    | '/playbook'
    | '/risk'
    | '/routing'
    | '/settings'
    | '/library/$slug'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/call'
    | '/compass'
    | '/deals'
    | '/discovery'
    | '/outputs'
    | '/playbook'
    | '/risk'
    | '/routing'
    | '/settings'
    | '/library/$slug'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallRoute: typeof CallRoute
  CompassRoute: typeof CompassRoute
  DealsRoute: typeof DealsRoute
  DiscoveryRoute: typeof DiscoveryRoute
  OutputsRoute: typeof OutputsRoute
  PlaybookRoute: typeof PlaybookRoute
  RiskRoute: typeof RiskRoute
  RoutingRoute: typeof RoutingRoute
  SettingsRoute: typeof SettingsRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass': {
      id: '/compass'
      path: '/compass'
      fullPath: '/compass'
      preLoaderRoute: typeof CompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallRoute: CallRoute,
  CompassRoute: CompassRoute,
  DealsRoute: DealsRoute,
  DiscoveryRoute: DiscoveryRoute,
  OutputsRoute: OutputsRoute,
  PlaybookRoute: PlaybookRoute,
  RiskRoute: RiskRoute,
  RoutingRoute: RoutingRoute,
  SettingsRoute: SettingsRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
